In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Series and Dataframe
a = pd.Series([1,2,3,4])
a

#  with lables
b = pd.Series([1,2,4,5],index=['a','b','c','d'])
print(b)

# actually 2 arrays that makes the series object, to look use values and index attributes.
print(b.values)
print(b.index)



a    1
b    2
c    4
d    5
dtype: int64
[1 2 4 5]
Index(['a', 'b', 'c', 'd'], dtype='object')


In [3]:
# selection of elements inside Series

print(b['b'])

print(b[1])

print(b[1:3])

#  to select multiple values using index lables,then pass list of index lables.
print(b[['b','c','d']])

# Assigning values to the Series
#  assgin value to the series object, can be done by select numeric index or corresponding lables

b[0]=233

b['b'] = 100

print(b)

print(b)




2
2
b    2
c    4
dtype: int64
b    2
c    4
d    5
dtype: int64
a    233
b    100
c      4
d      5
dtype: int64
a    233
b    100
c      4
d      5
dtype: int64


In [4]:
# Defining Pandas.Series object from Numpy array

c = np.array([1,2,3,4])

d = pd.Series(c)

print(d)

# holds reference to the array, if any changes, will also reflect in pandas series.

c[1]=100

print(d)

0    1
1    2
2    3
3    4
dtype: int32
0      1
1    100
2      3
3      4
dtype: int32


In [5]:
# filtering 

d[d==100]

1    100
dtype: int32

In [6]:
# Operations & Arithmatic functions

print(d+d)
print(d**2)

0      2
1    200
2      6
3      8
dtype: int32
0        1
1    10000
2        9
3       16
dtype: int32


In [7]:
# passsing pandas series to numpy maths function

np.log(d)

0    0.000000
1    4.605170
2    1.098612
3    1.386294
dtype: float64

In [8]:
# evaluating values inside Pandas Series

e = pd.Series([1,1,1,0,3,2,4],index=['a','a','a','x','c','b','d'] )

print(e.unique())
print(e.value_counts())

print(e.isin([0,1]))

print(e[e.isin([0,1])])


[1 0 3 2 4]
1    3
0    1
3    1
2    1
4    1
dtype: int64
a     True
a     True
a     True
x     True
c    False
b    False
d    False
dtype: bool
a    1
a    1
a    1
x    0
dtype: int64


In [9]:
# NAN 

f = pd.Series([1,2,np.nan, 4])

# using isnull and notnull functions

print(f.isnull()) 
print(f.notnull())

# extract only the notnull values

print(f[f.notnull()])


0    False
1    False
2     True
3    False
dtype: bool
0     True
1     True
2    False
3     True
dtype: bool
0    1.0
1    2.0
3    4.0
dtype: float64


In [10]:
# Series from Dictionary

g = {'red':1, 'green':2, 'blue':4}

h = pd.Series(g)

print(h)
# can also pass index seperatetly, Checks both key of the passed dictionary and values in the index array
# if if both value matches then will be included with given values in the dictionary otherwise include NaN
# to the missing array value.

i = ['red','green','blue','orange']

j = pd.Series(g, index=i)

print(j)




red      1
green    2
blue     4
dtype: int64
red       1.0
green     2.0
blue      4.0
orange    NaN
dtype: float64


In [11]:
# operations between Series
# will return new series object with the same lable or index

k = pd.Series({'blue':300})

j+k 

blue      304.0
green       NaN
orange      NaN
red         NaN
dtype: float64

In [12]:
# Pandas Dataframe

data = {'name':['py','js','ipy'],'marks':[1,2,3],'lang':['python','javascript','jupyter']}

l=pd.DataFrame({'name':['py','js','ipy'],'marks':[1,2,3],'lang':['python','javascript','jupyter']})


l=pd.DataFrame(data,columns=['lang','marks'])

# assigning custom index

l = pd.DataFrame(data, index=['a','b','c'])

l

name  marks        lang
a   py      1      python
b   js      2  javascript
c  ipy      3     jupyter

In [13]:
# alternate way of defining Dataframe

m = pd.DataFrame(np.arange(16).reshape(4,4), columns=['a','b','c','d'])
m

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [14]:
# Selecting Elements
print(m.columns)
print(m.index)
print(m.values)
print(m['b'])
print(m.c)
print(m.loc[2])

Index(['a', 'b', 'c', 'd'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
0     1
1     5
2     9
3    13
Name: b, dtype: int32
0     2
1     6
2    10
3    14
Name: c, dtype: int32
a     8
b     9
c    10
d    11
Name: 2, dtype: int32


In [15]:
print(m.loc[[1,3]])
type(m.loc[[1,3]])

    a   b   c   d
1   4   5   6   7
3  12  13  14  15


pandas.core.frame.DataFrame

In [16]:
print(m[1:2])

   a  b  c  d
1  4  5  6  7


In [17]:
m['b'][2]

9

In [18]:
#  assign name to index and column
m.index.name='id'
m.columns.name='alpha'
m

alpha   a   b   c   d
id                   
0       0   1   2   3
1       4   5   6   7
2       8   9  10  11
3      12  13  14  15

In [19]:
# adding new column

m['e']=0
m

alpha   a   b   c   d  e
id                      
0       0   1   2   3  0
1       4   5   6   7  0
2       8   9  10  11  0
3      12  13  14  15  0

In [20]:
m['e']=np.random.random(4)
m

alpha   a   b   c   d         e
id                             
0       0   1   2   3  0.301349
1       4   5   6   7  0.929805
2       8   9  10  11  0.389222
3      12  13  14  15  0.542117

In [21]:
# Membeship of a value

m.isin([5,'b'])

alpha      a      b      c      d      e
id                                      
0      False  False  False  False  False
1      False   True  False  False  False
2      False  False  False  False  False
3      False  False  False  False  False

In [22]:
# Delete a colunm

del m['e']
m

alpha   a   b   c   d
id                   
0       0   1   2   3
1       4   5   6   7
2       8   9  10  11
3      12  13  14  15

In [23]:
# filtering
m[m>4]

alpha     a     b     c     d
id                           
0       NaN   NaN   NaN   NaN
1       NaN   5.0   6.0   7.0
2       8.0   9.0  10.0  11.0
3      12.0  13.0  14.0  15.0

In [24]:
# dataframe from nested dictionary

nest_dict={'high':{2018:1,2019:2,2020:3},
            'low':{2018:0.5,2019:1.5,2020:2.5},
            'close':{2018:1,2019:2,2020:3,2021:4}}

n = pd.DataFrame(nest_dict)
n


high  low  close
2018   1.0  0.5      1
2019   2.0  1.5      2
2020   3.0  2.5      3
2021   NaN  NaN      4

In [25]:
# transpose dataframe

n.T

2018  2019  2020  2021
high    1.0   2.0   3.0   NaN
low     0.5   1.5   2.5   NaN
close   1.0   2.0   3.0   4.0

Dataframe's index objects are immmutable.

In [26]:
# index methods

print(n.index)
print(n.idxmin())
print(n.idxmax())


Int64Index([2018, 2019, 2020, 2021], dtype='int64')
high     2018
low      2018
close    2018
dtype: int64
high     2020
low      2020
close    2021
dtype: int64


In [27]:
o = pd.Series(range(6), index=['apple','banana', 'citrus','grape','apple', 'citrus' ])
print(o['citrus'])
# index is not unique beacuase it contains duplicates

o.index.is_unique

citrus    2
citrus    5
dtype: int64


False

In [28]:
# Reindexing, Dropping, Alignment

p = pd.Series([2,4,5,6], index=['one','two','three','four'])

q= p.reindex(['three', 'four', 'five', 'one'])

print(q)

three    5.0
four     6.0
five     NaN
one      2.0
dtype: float64


In [29]:
r = pd.Series(range(4), index=[0,2,3,5])
print(r)
# forward fill
s = r.reindex(range(4),method='ffill')
print(s)
#  backward fill
t = r.reindex(range(4), method='bfill')

print(t)

0    0
2    1
3    2
5    3
dtype: int64
0    0
1    0
2    1
3    2
dtype: int64
0    0
1    1
2    1
3    2
dtype: int64


In [30]:
u = pd.DataFrame({
    'open':[1,2,3,4,5],
    'close':[6,7,8,9,10],    
})
# u['vwap'] = u.apply(np.mean,axis=1)

v=u.reindex(range(5), method='ffill', columns=['close', 'vwap', 'open'])
# v['vwap'] = u.apply(np.mean, axis=1)
print(v)

   close  vwap  open
0      6   NaN     1
1      7   NaN     2
2      8   NaN     3
3      9   NaN     4
4     10   NaN     5


In [31]:
dropped_cit =o.drop('citrus')

dropped_o = o.drop(['banana', 'grape'])

dropped_cit



apple     0
banana    1
grape     3
apple     4
dtype: int64

In [32]:
w = pd.DataFrame(np.arange(16).reshape(4,4), columns=['a','b','c','d'])
w.drop(3)
w.drop([1,2])
w.drop(['c','d'], axis=1)

a   b
0   0   1
1   4   5
2   8   9
3  12  13

In [33]:
x = pd.Series(range(6),index=['a','b','d','c','k','i'])
print(x)
print(x.sort_index())
print(x.sort_index(ascending=False))

a    0
b    1
d    2
c    3
k    4
i    5
dtype: int64
a    0
b    1
c    3
d    2
i    5
k    4
dtype: int64
k    4
i    5
d    2
c    3
b    1
a    0
dtype: int64


In [34]:
# sort Values

w.sort_values(by='a', ascending=False)

a   b   c   d
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7
0   0   1   2   3

In [35]:
x.rank()

a    1.0
b    2.0
d    3.0
c    4.0
k    5.0
i    6.0
dtype: float64

In [36]:
x.rank(method='first')

a    1.0
b    2.0
d    3.0
c    4.0
k    5.0
i    6.0
dtype: float64

In [37]:
x.rank(ascending=False)

a    6.0
b    5.0
d    4.0
c    3.0
k    2.0
i    1.0
dtype: float64

In [38]:
# correlation and covariance

n.corr(),n.cov()


(       high  low  close
 high    1.0  1.0    1.0
 low     1.0  1.0    1.0
 close   1.0  1.0    1.0,
        high  low     close
 high    1.0  1.0  1.000000
 low     1.0  1.0  1.000000
 close   1.0  1.0  1.666667)

In [39]:
# assign, drop and fill NAN for Series and Dataframe
# Assign
y = pd.Series([1,2,4,np.nan,5])
y[5]=None
y
# drop
z= y.dropna()
y[y.notnull()]

aa = pd.DataFrame({"val":[1,np.nan,3,np.nan],
                    "rank":[1,2,3,np.nan]})
print(aa.dropna(how='all'))

# fill

print(aa.fillna('filled'))

print(aa.fillna({'val':'xx', 'rank':'yy'}))



   val  rank
0  1.0   1.0
1  NaN   2.0
2  3.0   3.0
      val    rank
0     1.0     1.0
1  filled     2.0
2     3.0     3.0
3  filled  filled
   val rank
0  1.0  1.0
1   xx  2.0
2  3.0  3.0
3   xx   yy


In [40]:
ab = pd.Series(np.random.random(8), index=[['sbi','sbi', 'sbi','hdfc','hdfc','icici','icici','icici'], [2021, 2020, 2019, 2020,2019, 2018, 2021,2020]])
ab

sbi    2021    0.012586
       2020    0.609032
       2019    0.802514
hdfc   2020    0.186779
       2019    0.320251
icici  2018    0.046151
       2021    0.005037
       2020    0.243384
dtype: float64

In [41]:
ab.index

MultiIndex([(  'sbi', 2021),
            (  'sbi', 2020),
            (  'sbi', 2019),
            ( 'hdfc', 2020),
            ( 'hdfc', 2019),
            ('icici', 2018),
            ('icici', 2021),
            ('icici', 2020)],
           )

In [42]:
ab['sbi']

2021    0.012586
2020    0.609032
2019    0.802514
dtype: float64

In [43]:
ab['sbi',2019]

0.8025139910253986

In [44]:
ab[:,2021]

sbi      0.012586
icici    0.005037
dtype: float64

In [45]:
ac = ab.unstack()
# Multilevel hierarchy series object becomes Dataframe after unstack 
print(type(ac))

print(ac)


<class 'pandas.core.frame.DataFrame'>
           2018      2019      2020      2021
hdfc        NaN  0.320251  0.186779       NaN
icici  0.046151       NaN  0.243384  0.005037
sbi         NaN  0.802514  0.609032  0.012586


In [46]:
# create multilevel Dataframe

ad = pd.DataFrame(np.arange(16).reshape(4,4), index=[['sbi','sbi','hdfc','hdfc'],[2021,2020,2021,2020]], columns=[['h','h','l','l'],['a','a','b','b']])
ad

h       l    
            a   a   b   b
sbi  2021   0   1   2   3
     2020   4   5   6   7
hdfc 2021   8   9  10  11
     2020  12  13  14  15

In [47]:
ad.index.names =['scrp', 'year']
ad.columns.names = ['normal', 'average']
ad

normal      h       l    
average     a   a   b   b
scrp year                
sbi  2021   0   1   2   3
     2020   4   5   6   7
hdfc 2021   8   9  10  11
     2020  12  13  14  15

In [48]:
ad.swaplevel('scrp', 'year')

normal      h       l    
average     a   a   b   b
year scrp                
2021 sbi    0   1   2   3
2020 sbi    4   5   6   7
2021 hdfc   8   9  10  11
2020 hdfc  12  13  14  15

In [49]:
ad.sort_index(level='year')

normal      h       l    
average     a   a   b   b
scrp year                
hdfc 2020  12  13  14  15
sbi  2020   4   5   6   7
hdfc 2021   8   9  10  11
sbi  2021   0   1   2   3

In [50]:
c1=pd.DataFrame(np.arange(0,12).reshape(3,4))

print(c1.to_html())

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>3</td>
    </tr>
    <tr>
      <th>1</th>
      <td>4</td>
      <td>5</td>
      <td>6</td>
      <td>7</td>
    </tr>
    <tr>
      <th>2</th>
      <td>8</td>
      <td>9</td>
      <td>10</td>
      <td>11</td>
    </tr>
  </tbody>
</table>


In [51]:
from pandas.io.pytables import HDFStore

z1 = pd.DataFrame(np.arange(0,6).reshape(2,3))

z2 =pd.DataFrame(np.arange(0,16).reshape(4,4))

store = HDFStore('mydata.h5')

store['obj1']= z1
store['obj2']=z2

print(store['obj1'])

HDF5ExtError: HDF5 error back trace

  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5F.c", line 509, in H5Fopen
    unable to open file
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5Fint.c", line 1652, in H5F_open
    unable to read superblock
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5Fsuper.c", line 623, in H5F__super_read
    truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048

End of HDF5 error back trace

Unable to open/create file 'mydata.h5'

In [ ]:
from pandas.io import  sql

dir(sql.SQLAlchemyEngine)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'insert_records']

In [ ]:
ba = pd.DataFrame({'id':['apple', 'banana', 'citrus', 'grape', 'avacodo'],
                    'price':np.arange(1,6)})

bb = pd.DataFrame({'id':['apple', 'banana', 'citrus', 'grape'],
                    
                    'stock':np.arange(4)})

pd.merge(ba,bb)

id  price  stock
0   apple      1      0
1  banana      2      1
2  citrus      3      2
3   grape      4      3

In [ ]:
# merging two dataframes with same columns, will not show any result

ba = pd.DataFrame({'id':['apple', 'banana', 'citrus', 'grape', 'avacodo'],
                    'price':np.arange(1,6)})

bb = pd.DataFrame({'id':['apple', 'banana', 'citrus', 'grape'],
                    
                    'price':np.arange(4)})

pd.merge(ba,bb)

Empty DataFrame
Columns: [id, price]
Index: []

In [ ]:
ba = pd.DataFrame({'id':['apple', 'banana', 'citrus', 'grape', 'avacodo'],
                    'price':np.arange(1,6)})

bb = pd.DataFrame({'id':['apple', 'banana', 'citrus', 'grape'],
                    
                    'price':np.arange(10,14)})

pd.merge(ba,bb, on='id')

id  price_x  price_y
0   apple        1       10
1  banana        2       11
2  citrus        3       12
3   grape        4       13

In [ ]:
ba = pd.DataFrame({'id':['apple', 'banana', 'citrus', 'grape', 'avacodo'],
                    'country':['ind','uk','us','brz','mex'],
                    'price':np.arange(1,6)})

bb = pd.DataFrame({'id':['apple', 'banana', 'citrus', 'grape'],
                    
                    'price':np.arange(10,14)})

pd.merge(ba,bb, on='id')

id country  price_x  price_y
0   apple     ind        1       10
1  banana      uk        2       11
2  citrus      us        3       12
3   grape     brz        4       13

In [ ]:
bc =pd.DataFrame({'id':['infy','wipro', 'hcl', 'tcs'],
                    'open':np.arange(101,105),
                    'close':np.arange(1,5)})
bd = pd.DataFrame({'exg':['infy','wipro', 'hcl', 'tcs', 'sbi'],
                    'high':np.arange(111,116)})

# merge() performs inner joins using diffeent column names
pd.merge(bc,bd, left_on='id', right_on='exg')
                   

id  open  close    exg  high
0   infy   101      1   infy   111
1  wipro   102      2  wipro   112
2    hcl   103      3    hcl   113
3    tcs   104      4    tcs   114

In [ ]:
be = pd.DataFrame({'scrip':['infy','sbi','sail', 'tcs', 'cipla'], 
                     'sector':['it','bank','metal', 'it', 'pharma'],
                     'price':np.arange(10,15)})

bf = pd.DataFrame({'scrip':['infy','sbi','sail', 'tcs', 'cipla', 'tatamotors', 'kotak'], 
                     'sector':['it','bank','metal', 'it', 'pharma', 'auto', 'bank'],
                     'high price':np.arange(20,27)})

pd.merge(be,bf,on='scrip', how='outer')


scrip sector_x  price sector_y  high price
0        infy       it   10.0       it          20
1         sbi     bank   11.0     bank          21
2        sail    metal   12.0    metal          22
3         tcs       it   13.0       it          23
4       cipla   pharma   14.0   pharma          24
5  tatamotors      NaN    NaN     auto          25
6       kotak      NaN    NaN     bank          26

In [ ]:
be = pd.DataFrame({'scrip':['infy','sbi','sail', 'tcs', 'cipla','coal'], 
                     'sector':['it','bank','metal', 'it', 'pharma','energy'],
                     'price':np.arange(10,16)})

bf = pd.DataFrame({'scrip':['infy','sbi','sail', 'tcs', 'cipla', 'tatamotors', 'kotak'], 
                     'sector':['it','bank','metal', 'it', 'pharma', 'auto', 'bank'],
                     'high price':np.arange(20,27)})

pd.merge(be,bf,on='scrip', how='inner')


scrip sector_x  price sector_y  high price
0   infy       it     10       it          20
1    sbi     bank     11     bank          21
2   sail    metal     12    metal          22
3    tcs       it     13       it          23
4  cipla   pharma     14   pharma          24

In [ ]:
# merging on an index
bg = pd.DataFrame({'item':['pen','pencil','paper','eraser'],
                    'color':['red','white','blue', 'orange'],
                    'price':np.arange(1,5)})

bh = pd.DataFrame({'item2':['pen','pencil','paper','eraser'],
                    'color2':['red','white','blue', 'orange'],
                    'price2':np.arange(1,5)}, index=[1,3,4,5])

pd.merge(bg,bh, left_index=True, right_index=True)

item   color  price   item2 color2  price2
1  pencil   white      2     pen    red       1
3  eraser  orange      4  pencil  white       2

In [ ]:
bg.join(bh)

item   color  price   item2 color2  price2
0     pen     red      1     NaN    NaN     NaN
1  pencil   white      2     pen    red     1.0
2   paper    blue      3     NaN    NaN     NaN
3  eraser  orange      4  pencil  white     2.0

In [ ]:
# concat

bi = np.arange(9).reshape(3,3)
bj =np.arange(9).reshape(3,3)+6

np.concatenate([bi,bj] ,axis=1)

np.concatenate([bi,bj])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
bk = pd.Series(np.arange(4), index=[1,2,3,4])
bl = pd.Series(np.arange(4), index=[5,6,7,8])

pd.concat([bk,bl])

1    0
2    1
3    2
4    3
5    0
6    1
7    2
8    3
dtype: int32

In [ ]:
# if axis =1 is set, then the result will be a dataframe.
pd.concat([bk,bl], axis=1)


0    1
1  0.0  NaN
2  1.0  NaN
3  2.0  NaN
4  3.0  NaN
5  NaN  0.0
6  NaN  1.0
7  NaN  2.0
8  NaN  3.0

In [ ]:
#  to form a hierachical index
pd.concat([bk,bl],keys=[1,2])

1  1    0
   2    1
   3    2
   4    3
2  5    0
   6    1
   7    2
   8    3
dtype: int32

In [ ]:
pd.concat([bk,bl], axis=1, keys=[1,2])

1    2
1  0.0  NaN
2  1.0  NaN
3  2.0  NaN
4  3.0  NaN
5  NaN  0.0
6  NaN  1.0
7  NaN  2.0
8  NaN  3.0

In [ ]:
pd.concat([bk,bl],axis=1)

0    1
1  0.0  NaN
2  1.0  NaN
3  2.0  NaN
4  3.0  NaN
5  NaN  0.0
6  NaN  1.0
7  NaN  2.0
8  NaN  3.0

In [ ]:
# combining
ser1 = pd.Series(np.arange(1,5), index=[1,2,3,4])
ser2 = pd.Series(np.arange(6,10), index=[1,3,4,5])

ser1.combine_first(ser2)
ser2.combine_first(ser1)

1    6.0
2    2.0
3    7.0
4    8.0
5    9.0
dtype: float64

In [ ]:
# combining_first also works with slicing 

ser2[:2].combine_first(ser1[:2])

1    6.0
2    2.0
3    7.0
dtype: float64

In [ ]:
ca = pd.DataFrame(np.arange(16).reshape(4,4), index=['sbi','nfl','tcs','upl',], columns=['open','close','high', 'low'])
print(ca)
cb = ca.stack()
print(cb)
cb.unstack()


     open  close  high  low
sbi     0      1     2    3
nfl     4      5     6    7
tcs     8      9    10   11
upl    12     13    14   15
sbi  open      0
     close     1
     high      2
     low       3
nfl  open      4
     close     5
     high      6
     low       7
tcs  open      8
     close     9
     high     10
     low      11
upl  open     12
     close    13
     high     14
     low      15
dtype: int32


open  close  high  low
sbi     0      1     2    3
nfl     4      5     6    7
tcs     8      9    10   11
upl    12     13    14   15

In [ ]:
# unstack on a different level
cb.unstack(1)

open  close  high  low
sbi     0      1     2    3
nfl     4      5     6    7
tcs     8      9    10   11
upl    12     13    14   15

In [ ]:
lf = pd.DataFrame({
    'scrip':['sbi','sbi','sbi','nfl','nfl','nfl','tcs','tcs','tcs','upl'],
    'order':['sell','buy','xxx','sell','buy','hold','sell','buy','hold','yyy'],
    'vol':np.random.rand(10)    
    })
lf
# print(np.random.rand(10))

lf.pivot('order','scrip')

vol                              
scrip       nfl       sbi       tcs       upl
order                                        
buy    0.291359  0.745823  0.352246       NaN
hold   0.343100       NaN  0.588385       NaN
sell   0.711297  0.567021  0.388753       NaN
xxx         NaN  0.604397       NaN       NaN
yyy         NaN       NaN       NaN  0.508316

In [ ]:
lf1 = pd.DataFrame({ 
'color':['white','white','white','red','red','red','black','black','black'],
'item':['ball','pen','mug','ball','pen','mug','ball','pen','mug'],
'value': np.random.rand(9)
})


lf1
# lf1.pivot('color','item')

color  item     value
0  white  ball  0.248587
1  white   pen  0.158824
2  white   mug  0.313834
3    red  ball  0.971527
4    red   pen  0.052292
5    red   mug  0.993649
6  black  ball  0.530601
7  black   pen  0.044750
8  black   mug  0.260796

In [ ]:
# Data transformation

# removing duplicate

#  "del df['column']" command for removing column and "drop (row)" command for row

df = pd.DataFrame({'color':['white', 'white','red', 'yellow', 'white' ],
                    'value':[1,2,3,4,2]})

df.duplicated()

# Extract duplicats

df[df.duplicated()]

# to removing duplicates

df.drop_duplicates()



color  value
0   white      1
1   white      2
2     red      3
3  yellow      4

In [ ]:
# Replacing values via mapping

# replace(), map(), rename()

df1 = pd.DataFrame({
    'scrip':['sbi','infy', 'tcs','coalindia'],
    'sector':['baks', 'it', 'it company', 'energy']
})

corrected_sector = {
    "baks":"banking",
    "it company":"it"
}

df1.replace(corrected_sector)



scrip   sector
0        sbi  banking
1       infy       it
2        tcs       it
3  coalindia   energy

In [ ]:
# adding values via mapping

df2 = pd.DataFrame({
    'scrip':['infy','sbi','tcs'],
    'sector':['it','banking', 'it']
})

close_price = {
    'infy':1600,
    'tcs':3300,
    'sbi':450
}

df2['close price']=df2['scrip'].map(close_price)

df2

scrip   sector  close price
0  infy       it         1600
1   sbi  banking          450
2   tcs       it         3300

In [ ]:
reindex={
    0:'first',
    1:"second",
    2:"third"
}

# renaming index

df3 = df2.rename(reindex)

df3

scrip   sector  close price
first   infy       it         1600
second   sbi  banking          450
third    tcs       it         3300

In [ ]:
#  for column renaming using column argument

recolumn = {
    'scrip':"ticker"
}

df5 = df3.rename(index=reindex, columns=recolumn)

df5

# to retain changes within the dataframe set inplace option to true

df3.rename(index=reindex, columns=recolumn, inplace=True)

df3

ticker   sector  close price
first    infy       it         1600
second    sbi  banking          450
third     tcs       it         3300

In [ ]:
# Discretization and Binning

# tranforms data into discrete catagories based ranges

results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87,100]
# boundary seperator
bins  = [0,25,50,75,100]

cat = pd.cut(results, bins)

cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (0, 25], (25, 50], (75, 100], (75, 100], (75, 100]]
Length: 18
Categories (4, interval[int64, right]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [ ]:
cat.codes

array([0, 1, 2, 2, 1, 3, 3, 0, 0, 2, 2, 1, 3, 0, 1, 3, 3, 3], dtype=int8)

In [ ]:
pd.value_counts(cat)

(75, 100]    6
(0, 25]      4
(25, 50]     4
(50, 75]     4
dtype: int64

In [ ]:
# without explicating bins

pd.cut(results, 5)

# but qcut ensures the number of occurances for each bin is equal

pd.qcut(results,5 )

[(2.999, 25.0], (25.0, 48.0], (48.0, 68.4], (48.0, 68.4], (25.0, 48.0], ..., (2.999, 25.0], (48.0, 68.4], (88.2, 100.0], (68.4, 88.2], (88.2, 100.0]]
Length: 18
Categories (5, interval[float64, right]): [(2.999, 25.0] < (25.0, 48.0] < (48.0, 68.4] < (68.4, 88.2] < (88.2, 100.0]]

In [ ]:
pd.value_counts(pd.qcut(results,5 ))

(2.999, 25.0]    4
(48.0, 68.4]     4
(88.2, 100.0]    4
(25.0, 48.0]     3
(68.4, 88.2]     3
dtype: int64

In [ ]:
# detecting anf filterng values

randframe = pd.DataFrame(np.random.randn(1000,3))

randframe.describe()

0            1            2
count  1000.000000  1000.000000  1000.000000
mean     -0.016580    -0.020440    -0.005574
std       0.988563     0.977496     1.023070
min      -3.191874    -3.087919    -3.981806
25%      -0.646181    -0.689909    -0.674428
50%      -0.043419    -0.034130     0.001685
75%       0.694785     0.620295     0.681855
max       2.826088     2.774592     2.841069

In [ ]:
df = pd.DataFrame({
    'color':['red','green','blue', 'red','green','blue'],
    'item':['ball','pen','ball', 'pen', 'pencil','ball'],
    'price1':np.random.random(6),
    'price2':np.random.random(6),
})

# Data Aggregation

grp = df['price1'].groupby(df['color'])

grp.mean()

grp.sum()


color
blue     0.982926
green    0.892780
red      0.832752
Name: price1, dtype: float64

In [ ]:
# Hierachial grouping

grp=df['price1'].groupby([df['color'],df['item']])

grp.groups

df1=grp.mean()

# df1.unstack()



In [ ]:
df[['price1','price2']].groupby(df['color']).mean()

price1    price2
color                    
blue   0.491463  0.835778
green  0.446390  0.501545
red    0.416376  0.461344

In [ ]:
# Group Iteration

for name, group in df.groupby('color'):

    print(name)
    print(group)

blue
  color  item    price1    price2
2  blue  ball  0.929058  0.851313
5  blue  ball  0.053868  0.820242
green
   color    item    price1    price2
1  green     pen  0.298765  0.235508
4  green  pencil  0.594015  0.767582
red
  color  item    price1    price2
0   red  ball  0.789385  0.306879
3   red   pen  0.043368  0.615810


In [ ]:
# Chain transformation
r1 = df['price1'].groupby(df['color']).mean()
print(r1)
type(r1)


color
blue     0.491463
green    0.446390
red      0.416376
Name: price1, dtype: float64


pandas.core.series.Series

In [ ]:
r2 = df.groupby(df['color']).mean() # entire dataframe is grouped here 

print(type(r2))
r2


<class 'pandas.core.frame.DataFrame'>


price1    price2
color                    
blue   0.491463  0.835778
green  0.446390  0.501545
red    0.416376  0.461344

In [ ]:
means = df.groupby(df['color']).mean().add_prefix('mean_')

means

mean_price1  mean_price2
color                          
blue      0.491463     0.835778
green     0.446390     0.501545
red       0.416376     0.461344

In [ ]:
# Functions on groups

g = df.groupby('color')
g['price1'].quantile(0.5)

color
blue     0.491463
green    0.446390
red      0.416376
Name: price1, dtype: float64

In [ ]:
# apply custom functions

def range(series):
    return series.max()-series.min()


g['price1'].agg(range)

color
blue     0.875190
green    0.295251
red      0.746017
Name: price1, dtype: float64

In [ ]:
g.agg(range)

d:\key\data analysis\da\lib\site-packages\pandas\core\groupby\generic.py:303: FutureWarning: Dropping invalid columns in SeriesGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the aggregating function.
  results[key] = self.aggregate(func)


price1    price2
color                    
blue   0.875190  0.031071
green  0.295251  0.532074
red    0.746017  0.308931

In [ ]:
g['price1'].agg(['mean','std',range])

mean       std     range
color                              
blue   0.491463  0.618852  0.875190
green  0.446390  0.208774  0.295251
red    0.416376  0.527514  0.746017

In [ ]:
# Advanced Data Agregation

df.groupby('color').transform(np.sum).add_prefix('total_')

total_item total_price1 total_price2
0    ballpen     0.832752     0.922689
1  penpencil      0.89278      1.00309
2   ballball     0.982926     1.671555
3    ballpen     0.832752     0.922689
4  penpencil      0.89278      1.00309
5   ballball     0.982926     1.671555

In [ ]:
df.groupby(['color','item']).apply(lambda x : s.max())

color  item  
blue   ball      2
green  pen       2
       pencil    2
red    ball      2
       pen       2
dtype: int64